name: Send POST every 5 minutes

on:
  schedule:
    - cron: "*/5 * * * *"  # Every 5 minutes
  workflow_dispatch:       # Optional: allows manual triggering

jobs:
  send_post:
    runs-on: ubuntu-latest
    steps:
      - name: Send POST request to /courses/course-list
        run: |
          curl -X POST https://sas-core-planner-latest.onrender.com/courses/course-list \
          -H "Content-Type: application/json" \
          -d '[["CCD"]]'
